import type { TargetPitchCurve, TargetPitchSegment } from "./target-segments";

const mockMelodyTargetSegmentsExample = [
  {
    targetId: "mock-melody-step-1-target-c4",
    sourceType: "mock-melody-step",
    segmentKind: "pitched-note",
    sourceNoteIds: ["melody-step-1"],
    noteName: "C4",
    frequencyHz: 261.63,
    expectedMidiNumber: 60,
    startTimeMs: 0,
    endTimeMs: 1000,
    startBeat: 0,
    endBeat: 1,
    measureNumber: 1,
    beatInMeasure: 1,
    displayLabel: "Step 1 · C4",
    centsToleranceGuide: 50,
    melodyStepIndex: 0,
    melodyStepId: "melody-step-1",
    shouldRenderAsTargetBlock: true,
    shouldCreateFormalScore: false,
  },
  {
    targetId: "mock-melody-step-2-target-d4",
    sourceType: "mock-melody-step",
    segmentKind: "pitched-note",
    sourceNoteIds: ["melody-step-2"],
    noteName: "D4",
    frequencyHz: 293.66,
    expectedMidiNumber: 62,
    startTimeMs: 1000,
    endTimeMs: 2000,
    startBeat: 1,
    endBeat: 2,
    measureNumber: 1,
    beatInMeasure: 2,
    displayLabel: "Step 2 · D4",
    centsToleranceGuide: 50,
    melodyStepIndex: 1,
    melodyStepId: "melody-step-2",
    shouldRenderAsTargetBlock: true,
    shouldCreateFormalScore: false,
  },
  {
    targetId: "mock-melody-step-3-target-e4",
    sourceType: "mock-melody-step",
    segmentKind: "pitched-note",
    sourceNoteIds: ["melody-step-3"],
    noteName: "E4",
    frequencyHz: 329.63,
    expectedMidiNumber: 64,
    startTimeMs: 2000,
    endTimeMs: 3000,
    startBeat: 2,
    endBeat: 3,
    measureNumber: 1,
    beatInMeasure: 3,
    displayLabel: "Step 3 · E4",
    centsToleranceGuide: 50,
    melodyStepIndex: 2,
    melodyStepId: "melody-step-3",
    shouldRenderAsTargetBlock: true,
    shouldCreateFormalScore: false,
  },
  {
    targetId: "mock-melody-step-4-target-c4-repeat",
    sourceType: "mock-melody-step",
    segmentKind: "pitched-note",
    sourceNoteIds: ["melody-step-4"],
    noteName: "C4",
    frequencyHz: 261.63,
    expectedMidiNumber: 60,
    startTimeMs: 3000,
    endTimeMs: 4000,
    startBeat: 3,
    endBeat: 4,
    measureNumber: 1,
    beatInMeasure: 4,
    displayLabel: "Step 4 · C4 repeated",
    centsToleranceGuide: 50,
    melodyStepIndex: 3,
    melodyStepId: "melody-step-4",
    shouldRenderAsTargetBlock: true,
    shouldCreateFormalScore: false,
  },
] satisfies TargetPitchSegment[];

export const mockMelodyTargetCurveExample = {
  curveId: "mock-melody-target-curve-example",
  sourceType: "mock-melody-step",
  tempoBpm: 60,
  timeSignature: "4/4",
  createdForPracticeModeOnly: true,
  segments: mockMelodyTargetSegmentsExample,
} satisfies TargetPitchCurve;
