"use client";

import { useMemo, useState } from "react";
import { adaptSeventhChordQuestionToActivity } from "../../lib/activity/legacyLocalActivityAdapter";
import { createLocalSeventhChordQuestion, getLocalSeventhChordAnswer, getLocalSeventhChordAnswerOptions, getLocalSeventhChordVariantCount } from "../../lib/practice/localEarTrainingSeventhChords";
import type { LocalPracticeDifficulty } from "../../lib/practice/localPracticeCatalog";
import type { ResolvedLocalPracticeCustomization } from "../../lib/practice/localPracticeCustomizer";
import type { LocalPracticeAnswerResult, LocalPracticeReviewTarget } from "../../lib/practice/localPracticeReviewQueue";
import { ActivityChoiceAnswerPanel } from "./ActivityChoiceAnswerPanel";
import { ActivityProtocolState } from "./ActivityProtocolState";
import { useChoiceActivitySession } from "./useChoiceActivitySession";
import { useLocalAudioPlayback } from "./useLocalAudioPlayback";
import { useLocalQuestionSchedule } from "./useLocalQuestionSchedule";
import { useLockedPracticeAnswer } from "./useLockedPracticeAnswer";

export function LocalEarTrainingSeventhChordPanel({ initialReviewTarget, customPractice, onLocalAnswerResult, onLeaveReviewTarget }: { initialReviewTarget?: Extract<LocalPracticeReviewTarget, { kind: "seventh-chord" }>; customPractice?: ResolvedLocalPracticeCustomization; onLocalAnswerResult?: (result: LocalPracticeAnswerResult) => void; onLeaveReviewTarget?: () => void }) {
  const activeCustomPractice = !initialReviewTarget && customPractice?.customization.kind === "seventh-chord" ? customPractice : undefined;
  const [difficulty, setDifficulty] = useState<LocalPracticeDifficulty>(initialReviewTarget?.difficulty ?? activeCustomPractice?.customization.difficulty ?? "基础");
  const [sequence, setSequence] = useState(initialReviewTarget?.sequence ?? 0);
  const [audioError, setAudioError] = useState("");
  const lock = useLockedPracticeAnswer<string | null>(null, (value) => value !== null);
  const { isPlaying, playbackState, play, stop } = useLocalAudioPlayback();
  const { questionIndex, sessionSeed, isReady } = useLocalQuestionSchedule({ itemCount: activeCustomPractice?.variantIds.length ?? getLocalSeventhChordVariantCount(difficulty), sequence, isCourseExercise: false, replaySeed: initialReviewTarget?.seed });
  const question = useMemo(() => createLocalSeventhChordQuestion({ difficulty, sequence, questionIndex, variantId: initialReviewTarget?.variantId ?? activeCustomPractice?.variantIds[questionIndex] }), [activeCustomPractice, difficulty, initialReviewTarget?.variantId, questionIndex, sequence]);
  const options = useMemo(() => getLocalSeventhChordAnswerOptions(difficulty).filter((option) => !activeCustomPractice || activeCustomPractice.answerOptionIds.includes(option.id)), [activeCustomPractice, difficulty]);
  const answer = useMemo(() => getLocalSeventhChordAnswer({ question, selectedOptionId: lock.selection }), [lock.selection, question]);
  const activity = useChoiceActivitySession(useMemo(() => adaptSeventhChordQuestionToActivity(question), [question]), `seventh:${question.id}`);
  const reset = () => { stop(); lock.reset(); activity.restart(); setAudioError(""); };
  const playQuestion = async () => { setAudioError(""); const error = await play((context, channel) => { const start = context.currentTime + .05; question.frequenciesHz.forEach((frequency) => { const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = "sine"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.0001, start); gain.gain.exponentialRampToValueAtTime(.09, start + .02); gain.gain.exponentialRampToValueAtTime(.0001, start + 1); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(start); oscillator.stop(start + 1.02); channel.trackSource(oscillator, [gain]); }); return 1100; }); if (error) setAudioError(error); };
  const reveal = () => { const selection = lock.reveal(); if (!selection) return; activity.checkChoice([selection]); if (onLocalAnswerResult && sessionSeed !== null) onLocalAnswerResult({ target: { kind: "seventh-chord", difficulty, seed: sessionSeed, sequence, variantId: question.variantId }, isCorrect: selection === question.answerOptionId }); };
  const next = () => { reset(); if (initialReviewTarget && onLeaveReviewTarget) onLeaveReviewTarget(); else setSequence((value) => value + 1); };
  return <section className="rounded-3xl border border-indigo-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-sm font-semibold tracking-wide text-indigo-700">P115 本地和声练耳</p><h2 className="mt-1 text-2xl font-bold text-slate-950">七和弦性质与转位听辨</h2><p className="mt-2 text-sm leading-6 text-slate-600">听四个本地合成音，辨认七和弦性质与最低音位置。只核对答案并解释结构，不生成正式分数。</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-indigo-50 p-4"><label className="text-sm font-semibold" htmlFor="seventh-difficulty">练习难度</label><select id="seventh-difficulty" className="mt-2 w-full rounded-xl border border-indigo-200 p-2" value={difficulty} disabled={Boolean(initialReviewTarget || activeCustomPractice)} onChange={(event) => { stop(); setDifficulty(event.target.value as LocalPracticeDifficulty); setSequence(0); lock.reset(); }}><option value="基础">基础：四种七和弦原位</option><option value="进阶">进阶：四种七和弦与第一转位</option><option value="挑战">挑战：四种七和弦与全部四种位置</option></select><p className="mt-4 text-sm text-indigo-950">本难度共 {activeCustomPractice?.variantCount ?? getLocalSeventhChordVariantCount(difficulty)} 个稳定组合；完整一轮前不重复。</p><button type="button" className="mt-4 w-full rounded-xl bg-indigo-700 px-4 py-3 font-bold text-white disabled:bg-indigo-300" disabled={!isReady || isPlaying} onClick={() => void playQuestion()}>{playbackState === "准备中" ? "正在准备声音…" : isPlaying ? "正在播放和弦…" : "播放题目"}</button><button type="button" className="mt-2 w-full rounded-xl border border-indigo-300 bg-white px-4 py-3 font-bold text-indigo-900 disabled:opacity-50" disabled={!isPlaying} onClick={stop}>停止播放</button>{audioError ? <p className="mt-3 text-sm text-rose-800">{audioError}</p> : null}</div><div className="rounded-2xl border border-slate-200 p-4"><p className="text-sm font-semibold text-slate-500">回答本题</p><ActivityChoiceAnswerPanel options={options} selectedOptionId={lock.selection} disabled={!isReady || lock.isAnswerVisible} accent="fuchsia" onChoose={(id) => { if (lock.choose(id)) activity.submitChoice([id]); }} /><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="rounded-xl bg-slate-900 px-4 py-2.5 font-bold text-white disabled:bg-slate-300" disabled={!answer.hasSelection} onClick={reveal}>查看本题答案</button><button type="button" className="rounded-xl border border-slate-300 px-4 py-2.5 font-bold" onClick={reset}>重置本题</button><button type="button" className="rounded-xl border border-indigo-300 px-4 py-2.5 font-bold text-indigo-900" disabled={!isReady} onClick={next}>{initialReviewTarget ? "返回随机练习" : "下一题"}</button></div><ActivityProtocolState session={activity.session} />{lock.isAnswerVisible ? <div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm leading-6"><p className="font-bold">本题答案：{answer.answerLabel}</p><p>{answer.explanation}</p><p className="text-slate-500">这是非评分答案说明，不代表准确率、等级、通过或失败。</p></div> : null}</div></div><p className="mt-5 text-sm text-slate-500">本机复练只保存题型、难度和稳定题目标识；不保存声音、具体选择或正式成绩。</p></section>;
}
